version: '3'
services:
    client:
        build: client
        command: python3 run_client.py
        links:
            - dummybot
        stdin_open: true
        tty: true
        volumes: 
            - './client:/client' 
    dummybot:
        build: dummybot
        command: python3 run_dummybot.py
        ports:
            - '80'
        volumes: 
            - './dummybot:/dummybot' 